spring:
  datasource:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MYBLOG


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.root2z.model.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true