spring:
  datasource:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MYBLOG
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: scr/main/java
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 40MB


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.root2z.model.entity

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true